[package]
name = "bevy_jam"
version = "0.0.0-dev"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[features]
dev = [
    "bevy/dynamic_linking",
]

[dependencies]
bevy = { version = "0.14", features = ["bevy_dynamic_plugin", "serialize", "multi_threaded"]} 

bevy_ecs_ldtk = "0.10.0"

bevy-inspector-egui = "0.25.0"

bevy_rapier2d = {version = "0.27.0", features = ["parallel", "debug-render-2d", "simd-stable", "serde"]}

num_enum = "0.7.2"

rand = "0.8.5"
rand_chacha = "0.3.1"
weighted_rand = "0.4.2"

serde = "1.0.203"
bincode = "1.3.3"

serde_json = "1.0.120"
bevy_hanabi = "0.12"
pathfinding = "4.10.0"

[[bin]]
name = "map"
path = "src/map_pathfind.rs"
